### ISSUE TITLE
Add SIDX: SmartIndex on SmartBCH

### ISSUE THREAD

**Issue by kratatomi** [mistswapdex/default-token-list#21]
- [X] I understand that token listing is not required to use the MISTswap Interface with a token.
- [X] I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
- [X] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: SmartBCH
Token Address (checkSum): 0xF05bD3d7709980f60CD5206BddFFA8553176dd29
Token Name (from contract): SmartIndex
Token Decimals (from contract): 18
Token Symbol (from contract): SIDX
MISTswap V2 Pair Address of Token: https://app.mistswap.fi/swap?inputCurrency=&outputCurrency=0xF05bD3d7709980f60CD5206BddFFA8553176dd29

Link to mistswapdex/assets PR: https://github.com/mistswapdex/assets/pull/31
Link to the official homepage of token: https://smartindex.cash/
Link to CoinMarketCap or CoinGecko page of token: none
Link to official Twitter account: https://t.me/smartindex_community

**Comment by kasumi-1** [comment]
merged - will be in next update to frontend.
