### ISSUE TITLE
Add VTO: Viegage Token on SmartBCH

### ISSUE THREAD

**Issue by acidsploit** [mistswapdex/default-token-list#25]
- [x] I understand that token listing is not required to use the MISTswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0xd8DE06b017857A821BA873D4F174B9580454f6c4
Token Name (from contract): Viegage Token
Token Decimals (from contract): 18
Token Symbol (from contract): VTO
MISTswap V2 Pair Address of Token: https://app.mistswap.fi/swap?inputCurrency=&outputCurrency=0xd8DE06b017857A821BA873D4F174B9580454f6c4

Link to mistswapdex/assets PR: https://github.com/mistswapdex/assets/pull/34
Link to the official homepage of token: https://viegage.com
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account: https://twitter.com/ViegageInc

**Comment by kasumi-1** [comment]
Added! Thanks
