### ISSUE TITLE
Add {GAME}: {Game} on {SMARTBCH}

### ISSUE THREAD

**Issue by Abuzik** [mistswapdex/default-token-list#30]
- [x] I understand that token listing is not required to use the MISTswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0xd2597a0bde31Ddec2440E256d8AA35eb63F1A9e3
Token Name (from contract): Game
Token Decimals (from contract): 18
Token Symbol (from contract): GAME
MISTswap V2 Pair Address of Token: 0x2ea9369daee963cebc0266ae8b98c3e015c59046

Link to mistswapdex/assets PR: assets/blockchains/smartbch/assets/0xd2597a0bde31Ddec2440E256d8AA35eb63F1A9e3/
Link to the official homepage of token: https://axiebch.com/game-token/
Link to CoinMarketCap or CoinGecko page of token: 
Link to official Twitter account: https://twitter.com/AxieBCH

**Comment by kasumi-1** [comment]
Please add some liquidity, thanks.

**Comment by kasumi-1** [comment]
This is now added, thanks.
