### ISSUE TITLE
Add TEEF: TEEF Token on SmartBCH

### ISSUE THREAD

**Issue by GiverofMemory** [mistswapdex/default-token-list#34]
- [x] I understand that token listing is not required to use the MISTswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: SmartBCH
Token Address (checkSum): 0xe691221eD15BA1E2491B552db955191789d9a8d9
Token Name (from contract): TEEF Token
Token Decimals (from contract): 4
Token Symbol (from contract): TEEF
MISTswap V2 Pair Address of Token: https://app.mistswap.fi/swap?outputCurrency=0xe691221eD15BA1E2491B552db955191789d9a8d9

Link to mistswapdex/assets PR: https://github.com/mistswapdex/assets/pull/42
Link to the official homepage of token: https://www.teefpowder.com/p/teef-token.html
Link to CoinMarketCap or CoinGecko page of token: none yet
Link to official Twitter account: none

**Comment by kasumi-1** [comment]
Please add sufficient liquidity, thanks.

**Comment by GiverofMemory** [comment]
Since you wont specify how much I'll move to other swaps.  Thanks anyway.
