### ISSUE TITLE
Add {$HAM}: {The HAM Token} on {smartbch.json}

### ISSUE THREAD

**Issue by ElDoradoTG** [mistswapdex/default-token-list#4]
Network:
{
    "chainId": 10000,
    "address": "0x252fd94f3Fb53D3D62F4FEc708501ACd59A57e52",
    "name": "The HAM Token",
    "symbol": "HAM",
    "decimals": 8,
    "logoURI": "https://ibb.co/Qdkdn88"
  }
] 

Twitter: https://twitter.com/HAM_Token
Telegram: https://t.me/HAM_Token_Chat
Website: https://linktr.ee/The_HAM_Token   (All  project related links are present here)
Logo/Icon: https://ibb.co/Qdkdn88
MISTswap V2 Pair Address of Token: BCH
Link to mistswapdex/assets PR: https://github.com/ElDoradoTG/assets/commit/b83bb6ce1beaa36984e732221fb760a670d64d95

**Comment by kasumi-1** [comment]
Hi! Please read instructions in README. Thanks
