### ISSUE TITLE
Add {SPACE}: {SPACE} on {sBCH}

### ISSUE THREAD

**Issue by starstrain** [mistswapdex/default-token-list#45]
- [x] I understand that token listing is not required to use the MISTswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0xB0c59E4B2249123b014c1C39D012BFCA58a8E1b7
Token Name (from contract):SPACE
Token Decimals (from contract):8
Token Symbol (from contract):SPACE
MISTswap V2 Pair Address of Token: 0xa0902ce72ba5c017F5F4180d15bBcaE8885D2f0F

Link to mistswapdex/assets PR: assets/blockchains/smartbch/assets/0xa0902ce72ba5c017F5F4180d15bBcaE8885D2f0F/logo.png
Link to the official homepage of token:https://timefoundation.net/Space-Finance
Link to CoinMarketCap or CoinGecko page of token:Not yet listed
Link to official Twitter account:https://twitter.com/SpaceTimeFi

**Comment by weilaiWEB** [comment]
[X ] 我了解使用带有代币的 MISTswap 接口不需要代币列表。
 我了解提交问题或增加流动性并不能保证添加到 MIST 默认代币列表中。
 我不会针对此列表请求对 Discord 进行 ping 操作。
请为您的令牌提供以下信息。

网络：smartBCH 代
币地址（校验和）：0x2f0c5f437297f155492e711fc8d2d91f8735f255 代
币名称（来自合约）：未来 代
币小数（来自合约）：18 代
币符号（来自合约）：web
MISTswap V2 代币对地址：[https : //app.mistswap.fi /swap?](https://app.mistswap.fi/swap)inputCurrency=&outputCurrency=0x20539E145b86A388683CB067dE576303aEC6DdE3

链接到mistswapdex/assets PR：assets/blockchains/smartbch/assets/0x20539E145b86A388683CB067dE576303aEC6DdE3/logo.png
链接到代币官方主页：
链接到代币的CoinMarketCap或CoinGecko页面：尚未列出
链接到官方推特账号：[https : //twitter.com/PumpParrots](https://twitter.com/weilai36509128/status/1481656534145069058?s=20)

**Comment by weilaiWEB** [comment]
[X ] I understand that token listing is not required to use the MISTswap Interface with a token.
 I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
 I will not ping the Discord about this listing request.
Please provide the following information for your token.

Network: smartBCH
Token Address (checkSum): 0x2f0c5f437297f155492e711fc8d2d91f8735f255
Token Name (from contract): 未来
Token Decimals (from contract): 18
Token Symbol (from contract): web
MISTswap V2 Pair Address of Token: https://app.mistswap.fi/swap?inputCurrency=&outputCurrency=0x20539E145b86A388683CB067dE576303aEC6DdE3

Link to mistswapdex/assets PR: assets/blockchains/smartbch/assets/0x20539E145b86A388683CB067dE576303aEC6DdE3/logo.png
Link to the official homepage of token: www.pumpitup.cash
Link to CoinMarketCap or CoinGecko page of token: not yet listed
Link to official Twitter account: https://twitter.com/weilai36509128/status/1481656534145069058?s=20

**Comment by kasumi-1** [comment]
This was added in 637d11b884f3a3c1e4f9c42361a61fbc3236c88e - thanks.
