### ISSUE TITLE
Add {TOKEN_SYMBOL}: {TOKEN_NAME} on {NETWORK}

### ISSUE THREAD

**Issue by bchdao** [mistswapdex/default-token-list#47]
- [x] I understand that token listing is not required to use the MISTswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network:
Token Address (checkSum):0xe5643aAF41ed9e5a56C3D5D1a049b43Ac69950b2
Token Name (from contract):BCHDAO
Token Decimals (from contract):18
Token Symbol (from contract):BCHDAO
MISTswap V2 Pair Address of Token:https://app.mistswap.fi/swap?inputCurrency=0xe5643aAF41ed9e5a56C3D5D1a049b43Ac69950b2&outputCurrency=

Link to mistswapdex/assets PR:assets/blockchains/smartbch/assets/0xe5643aAF41ed9e5a56C3D5D1a049b43Ac69950b2/
Link to the official homepage of token:https://www.bchdao.cash. (Q2 is online)
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account:https://twitter.com/bchdaocash

**Comment by kasumi-1** [comment]
This was added, thanks,
