### ISSUE TITLE
Add {BPAD}: {BCHPad} on {Smart BitcoinCash}

### ISSUE THREAD

**Issue by sVNT-Token** [mistswapdex/default-token-list#5]
- [x] I understand that token listing is not required to use the MISTswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: 10000
Token Address (0xe4EC235195aa1378567F4E8B301EAd6D90Aaa893):
Token Name (BCHPad):
Token Decimals (18):
Token Symbol (BPAD):
MISTswap V2 Pair Address of Token: null

Link to mistswapdex/assets PR: https://github.com/mistswapdex/assets/pull/3
Link to the official homepage of token: https://www.bchpad.cash/
Link to CoinMarketCap or CoinGecko page of token: null
Link to official Twitter account: https://twitter.com/bchpad

**Comment by kasumi-1** [comment]
Hi! Please read instructions in README. Thanks
