### ISSUE TITLE
Add {EVE}: {expected value entropy} on {smartbch}

### ISSUE THREAD

**Issue by PokerJ0k3r** [mistswapdex/default-token-list#53]
- [x] I understand that token listing is not required to use the MISTswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: smartbch
Token Address (checkSum): 0x7b82A3b1417Cd21E67f745917a80cC0f53277B8C
Token Name (from contract): expected value entropy
Token Decimals (from contract): 7 
Token Symbol (from contract): EVE
MISTswap V2 Pair Address of Token: 0x380094357328488781a0FB31c271a13DB7357c1E
Link to mistswapdex/assets PR: blockchains/smartbch/assets/0x7b82A3b1417Cd21E67f745917a80cC0f53277B8C/logo.png
Link to the official homepage of token: evecoin.info
Link to CoinMarketCap or CoinGecko page of token: marketcap.cash/token/eve
Link to official Twitter account: twitter.com/pokerjok3r
<img width="740" alt="C93FB99A-FB8B-4028-8140-6B412CA6E41D" src="https://user-images.githubusercontent.com/96651874/151033565-c41ddc74-2ac8-488b-8352-73df55ddcb08.png">

**Comment by PokerJ0k3r** [comment]
thankyou so much
![pixil-frame-0 (5)](https://user-images.githubusercontent.com/96651874/151033668-d1ceba2e-99c4-4d6e-b479-2e9b3b378bee.png)

**Comment by kasumi-1** [comment]
This was added in 3334f61fac5cefdcef41eba11497f1f2c8b8c091 thanks
