### ISSUE TITLE
Add {EVE}: {Expected Value Entropy} on {SmartBCH}

### ISSUE THREAD

**Issue by PokerJ0k3r** [mistswapdex/default-token-list#54]
- [x] I understand that token listing is not required to use the MISTswap Interface with a token.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**

Network: SmartBCH
Token Address (checkSum): 
<img width="740" alt="C93FB99A-FB8B-4028-8140-6B412CA6E41D" src="https://user-images.githubusercontent.com/96651874/151091005-685007bf-022e-47c7-af22-eff28c785e75.png">
0x7b82A3b1417Cd21E67f745917a80cC0f53277B8C
Token Name (from contract): Expected Value Entropy
Token Decimals (from contract): 7
Token Symbol (from contract): EVE
MISTswap V2 Pair Address of Token: 0x380094357328488781a0FB31c271a13DB7357c1E
Link to mistswapdex/assets PR: blockchains/smartbch/assets/0x7b82A3b1417Cd21E67f745917a80cC0f53277B8C/logo.png
<img width="740" alt="C93FB99A-FB8B-4028-8140-6B412CA6E41D" src="https://user-images.githubusercontent.com/96651874/151090880-c2914f00-cec4-475d-9de1-a5f454e2c9a1.png">
Link to the official homepage of token: evecoin.info
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account: twitter.com/pokerjok3r

**Comment by kasumi-1** [comment]
This was added in 3334f61fac5cefdcef41eba11497f1f2c8b8c091 thanks
