### ISSUE TITLE
gBCH: Goblins BCH on smartBCH

### ISSUE THREAD

**Issue by trankuilized** [mistswapdex/default-token-list#62]
- [x ] I understand that token listing is not required to use the MISTswap Interface with a token.
- [ x] I understand that filing an issue or adding liquidity does not guarantee addition to the MIST default token list.
- [ x] I will not ping the Discord about this listing request.
- [ x] I have made sure there is a minimum of at least 5 BCH of liquidity available for this token on MISTswap.

**Please provide the following information for your token.**

Network:
Token Address (checkSum): 0x009dC89aC501a62C4FaaF7196aeE90CF79B6fC7c
Token Name (from contract): Goblins BCH
Token Decimals (from contract): 18
Token Symbol (from contract): gBCH
MISTswap V2 Pair Address of Token: https://app.mistswap.fi/swap?inputCurrency=0x56381cB87C8990971f3e9d948939e1a95eA113a3&outputCurrency=0x009dC89aC501a62C4FaaF7196aeE90CF79B6fC7c

Link to mistswapdex/assets PR: https://github.com/mistswapdex/assets/pull/74
Link to the official homepage of token: https://goblins.cash
Link to CoinMarketCap or CoinGecko page of token:
Link to official Twitter account: https://twitter.com/GoblinsCash

**Comment by kasumi-1** [comment]
Added in ff49e4f2c8d4cefff0c7df7997d64be2ea8086cc - thank you!
